/*
 * generated by Xtext
 */
package fr.esir.imse.ui.contentassist

import fr.esir.imse.ui.contentassist.AbstractPollSystemUIProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PollSystemUIProposalProvider extends AbstractPollSystemUIProposalProvider {
}
