/*
 * generated by Xtext
 */
package fr.esir.imse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PollSystemUIUiModule extends fr.esir.imse.ui.AbstractPollSystemUIUiModule {
	public PollSystemUIUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
