/*
* generated by Xtext
*/
package fr.esir.imse;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PollSystemUIStandaloneSetup extends PollSystemUIStandaloneSetupGenerated{

	public static void doSetup() {
		new PollSystemUIStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

