/*
 * generated by Xtext
 */
package fr.esir.imse;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PollSystemUIRuntimeModule extends fr.esir.imse.AbstractPollSystemUIRuntimeModule {

}
